### ISSUE TITLE
Integrate font family groups into the language

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concisecss#1]
Perhaps something like:

```scss
h1 {
  font-family: heading;
}

body {
  font-family: body;
}

code {
  font-family: monospaced;
}
```
